*ods pdf file="C:\Users\chcww\Downloads\";
%let indir=C:\Users\chcww\Downloads\;
proc import datafile="&indir\take.csv" out =take 
dbms=csv replace;
getnames=yes;
run;
proc print data=take (obs=10);
run;
/*manova*/
proc glm;
class repeater;
model 
chain
offer
market
offervalue
buy_total_amount
buy_total_avgamount
buy_total_freq
buy_total_daydiff
buy_total_maxDay
buy_total_CT
buy_total_OZ
buy_total_LT
buy_total_amount_30
buy_total_avgamount_30
buy_total_freq_30
buy_total_CT_30
buy_total_OZ_30
buy_total_LT_30
buy_total_amount_60
buy_total_avgamount_60
buy_total_freq_60
buy_total_CT_60
buy_total_OZ_60
buy_total_LT_60
buy_total_amount_90
buy_total_avgamount_90
buy_total_freq_90
buy_total_CT_90
buy_total_OZ_90
buy_total_LT_90
buy_total_amount_120
buy_total_avgamount_120
buy_total_freq_120
buy_total_CT_120
buy_total_OZ_120
buy_total_LT_120
buy_total_amount_150
buy_total_avgamount_150
buy_total_freq_150
buy_total_CT_150
buy_total_OZ_150
buy_total_LT_150
buy_total_amount_180
buy_total_avgamount_180
buy_total_freq_180
buy_total_CT_180
buy_total_OZ_180
buy_total_LT_180
buy_company_amount
buy_company_avgamount
buy_company_freq
buy_company_daydiff
buy_company_CT
buy_company_OZ
buy_company_LT
buy_brand_amount
buy_brand_avgamount
buy_brand_freq
buy_brand_daydiff
buy_brand_CT
buy_brand_OZ
buy_brand_LT
buy_category_amount
buy_category_avgamount
buy_category_freq
buy_category_daydiff
buy_category_CT
buy_category_OZ
buy_category_LT
buy_company_amount_30
buy_company_avgamount_30
buy_company_freq_30
buy_company_CT_30
buy_company_OZ_30
buy_company_LT_30
buy_brand_amount_30
buy_brand_avgamount_30
buy_brand_freq_30
buy_brand_CT_30
buy_brand_OZ_30
buy_brand_LT_30
buy_category_amount_30
buy_category_avgamount_30
buy_category_freq_30
buy_category_CT_30
buy_category_OZ_30
buy_category_LT_30
buy_company_amount_60
buy_company_avgamount_60
buy_company_freq_60
buy_company_CT_60
buy_company_OZ_60
buy_company_LT_60
buy_brand_amount_60
buy_brand_avgamount_60
buy_brand_freq_60
buy_brand_CT_60
buy_brand_OZ_60
buy_brand_LT_60
buy_category_amount_60
buy_category_avgamount_60
buy_category_freq_60
buy_category_CT_60
buy_category_OZ_60
buy_category_LT_60
buy_company_amount_90
buy_company_avgamount_90
buy_company_freq_90
buy_company_CT_90
buy_company_OZ_90
buy_company_LT_90
buy_brand_amount_90
buy_brand_avgamount_90
buy_brand_freq_90
buy_brand_CT_90
buy_brand_OZ_90
buy_brand_LT_90
buy_category_amount_90
buy_category_avgamount_90
buy_category_freq_90
buy_category_CT_90
buy_category_OZ_90
buy_category_LT_90
buy_company_amount_120
buy_company_avgamount_120
buy_company_freq_120
buy_company_CT_120
buy_company_OZ_120
buy_company_LT_120
buy_brand_amount_120
buy_brand_avgamount_120
buy_brand_freq_120
buy_brand_CT_120
buy_brand_OZ_120
buy_brand_LT_120
buy_category_amount_120
buy_category_avgamount_120
buy_category_freq_120
buy_category_CT_120
buy_category_OZ_120
buy_category_LT_120
buy_company_amount_150
buy_company_avgamount_150
buy_company_freq_150
buy_company_CT_150
buy_company_OZ_150
buy_company_LT_150
buy_brand_amount_150
buy_brand_avgamount_150
buy_brand_freq_150
buy_brand_CT_150
buy_brand_OZ_150
buy_brand_LT_150
buy_category_amount_150
buy_category_avgamount_150
buy_category_freq_150
buy_category_CT_150
buy_category_OZ_150
buy_category_LT_150
buy_company_amount_180
buy_company_avgamount_180
buy_company_freq_180
buy_company_CT_180
buy_company_OZ_180
buy_company_LT_180
buy_brand_amount_180
buy_brand_avgamount_180
buy_brand_freq_180
buy_brand_CT_180
buy_brand_OZ_180
buy_brand_LT_180
buy_category_amount_180
buy_category_avgamount_180
buy_category_freq_180
buy_category_CT_180
buy_category_OZ_180
buy_category_LT_180
not_buy_company
not_buy_brand
not_buy_category
not_buy_company_brand
not_buy_company_category
not_buy_brand_category = repeater;
manova h=repeater/ printh printe;
run;

/*corr*/
proc corr data=take out=take_cor;
var offervalue
buy_total_amount
buy_total_avgamount
buy_total_freq
buy_total_daydiff
buy_total_maxDay
buy_total_CT
buy_total_OZ
buy_total_LT
buy_total_amount_30
buy_total_avgamount_30
buy_total_freq_30
buy_total_CT_30
buy_total_OZ_30
buy_total_LT_30
buy_total_amount_60
buy_total_avgamount_60
buy_total_freq_60
buy_total_CT_60
buy_total_OZ_60
buy_total_LT_60
buy_total_amount_90
buy_total_avgamount_90
buy_total_freq_90
buy_total_CT_90
buy_total_OZ_90
buy_total_LT_90
buy_total_amount_120
buy_total_avgamount_120
buy_total_freq_120
buy_total_CT_120
buy_total_OZ_120
buy_total_LT_120
buy_total_amount_150
buy_total_avgamount_150
buy_total_freq_150
buy_total_CT_150
buy_total_OZ_150
buy_total_LT_150
buy_total_amount_180
buy_total_avgamount_180
buy_total_freq_180
buy_total_CT_180
buy_total_OZ_180
buy_total_LT_180
buy_company_amount
buy_company_avgamount
buy_company_freq
buy_company_daydiff
buy_company_CT
buy_company_OZ
buy_company_LT
buy_brand_amount
buy_brand_avgamount
buy_brand_freq
buy_brand_daydiff
buy_brand_CT
buy_brand_OZ
buy_brand_LT
buy_category_amount
buy_category_avgamount
buy_category_freq
buy_category_daydiff
buy_category_CT
buy_category_OZ
buy_category_LT
buy_company_amount_30
buy_company_avgamount_30
buy_company_freq_30
buy_company_CT_30
buy_company_OZ_30
buy_company_LT_30
buy_brand_amount_30
buy_brand_avgamount_30
buy_brand_freq_30
buy_brand_CT_30
buy_brand_OZ_30
buy_brand_LT_30
buy_category_amount_30
buy_category_avgamount_30
buy_category_freq_30
buy_category_CT_30
buy_category_OZ_30
buy_category_LT_30
buy_company_amount_60
buy_company_avgamount_60
buy_company_freq_60
buy_company_CT_60
buy_company_OZ_60
buy_company_LT_60
buy_brand_amount_60
buy_brand_avgamount_60
buy_brand_freq_60
buy_brand_CT_60
buy_brand_OZ_60
buy_brand_LT_60
buy_category_amount_60
buy_category_avgamount_60
buy_category_freq_60
buy_category_CT_60
buy_category_OZ_60
buy_category_LT_60
buy_company_amount_90
buy_company_avgamount_90
buy_company_freq_90
buy_company_CT_90
buy_company_OZ_90
buy_company_LT_90
buy_brand_amount_90
buy_brand_avgamount_90
buy_brand_freq_90
buy_brand_CT_90
buy_brand_OZ_90
buy_brand_LT_90
buy_category_amount_90
buy_category_avgamount_90
buy_category_freq_90
buy_category_CT_90
buy_category_OZ_90
buy_category_LT_90
buy_company_amount_120
buy_company_avgamount_120
buy_company_freq_120
buy_company_CT_120
buy_company_OZ_120
buy_company_LT_120
buy_brand_amount_120
buy_brand_avgamount_120
buy_brand_freq_120
buy_brand_CT_120
buy_brand_OZ_120
buy_brand_LT_120
buy_category_amount_120
buy_category_avgamount_120
buy_category_freq_120
buy_category_CT_120
buy_category_OZ_120
buy_category_LT_120
buy_company_amount_150
buy_company_avgamount_150
buy_company_freq_150
buy_company_CT_150
buy_company_OZ_150
buy_company_LT_150
buy_brand_amount_150
buy_brand_avgamount_150
buy_brand_freq_150
buy_brand_CT_150
buy_brand_OZ_150
buy_brand_LT_150
buy_category_amount_150
buy_category_avgamount_150
buy_category_freq_150
buy_category_CT_150
buy_category_OZ_150
buy_category_LT_150
buy_company_amount_180
buy_company_avgamount_180
buy_company_freq_180
buy_company_CT_180
buy_company_OZ_180
buy_company_LT_180
buy_brand_amount_180
buy_brand_avgamount_180
buy_brand_freq_180
buy_brand_CT_180
buy_brand_OZ_180
buy_brand_LT_180
buy_category_amount_180
buy_category_avgamount_180
buy_category_freq_180
buy_category_CT_180
buy_category_OZ_180
buy_category_LT_180
not_buy_company
not_buy_brand
not_buy_category
not_buy_company_brand
not_buy_company_category
not_buy_brand_category;
run;

/*take FA*/

proc factor data=take nfactor=13 scree rotate=varimex out=take1;
var offervalue
buy:
not_buy:;
run;



proc factor data=take nfactor=13 scree rotate=varimex out=take1;
var buy_total_amount
buy_total_freq
buy_total_CT
buy_total_OZ
buy_total_amount_30
buy_total_freq_30
buy_total_CT_30
buy_total_OZ_30
buy_total_amount_60
buy_total_freq_60
buy_total_CT_60
buy_total_OZ_60
buy_total_amount_90
buy_total_freq_90
buy_total_CT_90
buy_total_OZ_90
buy_total_amount_120
buy_total_freq_120
buy_total_CT_120
buy_total_OZ_120
buy_total_amount_150
buy_total_freq_150
buy_total_CT_150
buy_total_OZ_150
buy_total_amount_180
buy_total_freq_180
buy_total_CT_180
buy_total_OZ_180
buy_company_amount
buy_company_freq
buy_company_CT
buy_company_OZ
buy_brand_amount
buy_brand_freq
buy_brand_CT
buy_brand_OZ
buy_category_amount
buy_category_freq
buy_category_OZ
buy_company_amount_30
buy_company_freq_30
buy_company_CT_30
buy_company_OZ_30
buy_brand_amount_30
buy_brand_freq_30
buy_brand_CT_30
buy_brand_OZ_30
buy_category_amount_30
buy_category_freq_30
buy_category_CT_30
buy_category_OZ_30
buy_company_amount_60
buy_company_freq_60
buy_company_CT_60
buy_company_OZ_60
buy_brand_amount_60
buy_brand_freq_60
buy_brand_CT_60
buy_brand_OZ_60
buy_category_amount_60
buy_category_freq_60
buy_category_CT_60
buy_category_OZ_60
buy_company_amount_90
buy_company_freq_90
buy_company_CT_90
buy_company_OZ_90
buy_brand_amount_90
buy_brand_freq_90
buy_brand_CT_90
buy_brand_OZ_90
buy_category_amount_90
buy_category_freq_90
buy_category_CT_90
buy_category_OZ_90
buy_company_amount_120
buy_company_freq_120
buy_company_CT_120
buy_company_OZ_120
buy_brand_amount_120
buy_brand_freq_120
buy_brand_CT_120
buy_brand_OZ_120
buy_category_amount_120
buy_category_freq_120
buy_category_CT_120
buy_category_OZ_120
buy_company_amount_150
buy_company_freq_150
buy_company_CT_150
buy_company_OZ_150
buy_brand_amount_150
buy_brand_freq_150
buy_brand_CT_150
buy_brand_OZ_150
buy_category_amount_150
buy_category_freq_150
buy_category_CT_150
buy_category_OZ_150
buy_company_amount_180
buy_company_freq_180
buy_company_CT_180
buy_company_OZ_180
buy_brand_amount_180
buy_brand_freq_180
buy_brand_CT_180
buy_brand_OZ_180
buy_category_amount_180
buy_category_freq_180
buy_category_CT_180
buy_category_OZ_180;
run;



proc factor data=take nfactor=3 scree rotate=varimex out=take1;
var offervalue
buy_total_amount
buy_total_avgamount
buy_total_freq
buy_total_daydiff
buy_total_maxDay
buy_total_CT
buy_total_OZ
buy_total_LT
buy_total_amount_30
buy_total_avgamount_30
buy_total_freq_30
buy_total_CT_30
buy_total_OZ_30
buy_total_LT_30
buy_total_amount_60
buy_total_avgamount_60
buy_total_freq_60
buy_total_CT_60
buy_total_OZ_60
buy_total_LT_60
buy_total_amount_90
buy_total_avgamount_90
buy_total_freq_90
buy_total_CT_90
buy_total_OZ_90
buy_total_LT_90
buy_total_amount_120
buy_total_avgamount_120
buy_total_freq_120
buy_total_CT_120
buy_total_OZ_120
buy_total_LT_120
buy_total_amount_150
buy_total_avgamount_150
buy_total_freq_150
buy_total_CT_150
buy_total_OZ_150
buy_total_LT_150
buy_total_amount_180
buy_total_avgamount_180
buy_total_freq_180
buy_total_CT_180
buy_total_OZ_180
buy_total_LT_180
buy_company_amount
buy_company_avgamount
buy_company_freq
buy_company_daydiff
buy_company_CT
buy_company_OZ
buy_company_LT
buy_brand_amount
buy_brand_avgamount
buy_brand_freq
buy_brand_daydiff
buy_brand_CT
buy_brand_OZ
buy_brand_LT
buy_category_amount
buy_category_avgamount
buy_category_freq
buy_category_daydiff
buy_category_CT
buy_category_OZ
buy_category_LT
buy_company_amount_30
buy_company_avgamount_30
buy_company_freq_30
buy_company_CT_30
buy_company_OZ_30
buy_company_LT_30
buy_brand_amount_30
buy_brand_avgamount_30
buy_brand_freq_30
buy_brand_CT_30
buy_brand_OZ_30
buy_brand_LT_30
buy_category_amount_30
buy_category_avgamount_30
buy_category_freq_30
buy_category_CT_30
buy_category_OZ_30
buy_category_LT_30
buy_company_amount_60
buy_company_avgamount_60
buy_company_freq_60
buy_company_CT_60
buy_company_OZ_60
buy_company_LT_60
buy_brand_amount_60
buy_brand_avgamount_60
buy_brand_freq_60
buy_brand_CT_60
buy_brand_OZ_60
buy_brand_LT_60
buy_category_amount_60
buy_category_avgamount_60
buy_category_freq_60
buy_category_CT_60
buy_category_OZ_60
buy_category_LT_60
buy_company_amount_90
buy_company_avgamount_90
buy_company_freq_90
buy_company_CT_90
buy_company_OZ_90
buy_company_LT_90
buy_brand_amount_90
buy_brand_avgamount_90
buy_brand_freq_90
buy_brand_CT_90
buy_brand_OZ_90
buy_brand_LT_90
buy_category_amount_90
buy_category_avgamount_90
buy_category_freq_90
buy_category_CT_90
buy_category_OZ_90
buy_category_LT_90
buy_company_amount_120
buy_company_avgamount_120
buy_company_freq_120
buy_company_CT_120
buy_company_OZ_120
buy_company_LT_120
buy_brand_amount_120
buy_brand_avgamount_120
buy_brand_freq_120
buy_brand_CT_120
buy_brand_OZ_120
buy_brand_LT_120
buy_category_amount_120
buy_category_avgamount_120
buy_category_freq_120
buy_category_CT_120
buy_category_OZ_120
buy_category_LT_120
buy_company_amount_150
buy_company_avgamount_150
buy_company_freq_150
buy_company_CT_150
buy_company_OZ_150
buy_company_LT_150
buy_brand_amount_150
buy_brand_avgamount_150
buy_brand_freq_150
buy_brand_CT_150
buy_brand_OZ_150
buy_brand_LT_150
buy_category_amount_150
buy_category_avgamount_150
buy_category_freq_150
buy_category_CT_150
buy_category_OZ_150
buy_category_LT_150
buy_company_amount_180
buy_company_avgamount_180
buy_company_freq_180
buy_company_CT_180
buy_company_OZ_180
buy_company_LT_180
buy_brand_amount_180
buy_brand_avgamount_180
buy_brand_freq_180
buy_brand_CT_180
buy_brand_OZ_180
buy_brand_LT_180
buy_category_amount_180
buy_category_avgamount_180
buy_category_freq_180
buy_category_CT_180
buy_category_OZ_180
buy_category_LT_180
not_buy_company
not_buy_brand
not_buy_category
not_buy_company_brand
not_buy_company_category
not_buy_brand_category;
run;
/*canonical*/
/*buy_total_amount
buy_total_avgamount
buy_total_freq
buy_total_daydiff*/
proc cancorr data=take all vprefix=u wprefix=v;
var buy_total_daydiff
buy_total_maxDay
buy_total_CT
buy_total_OZ
buy_total_LT; 
with buy_total_amount
buy_total_avgamount;
run;
proc cancorr data=take all vprefix=u wprefix=v;
var buy_total_daydiff
buy_total_maxDay
buy_total_CT
buy_total_OZ
buy_total_LT; 
with buy_total_avgamount
buy_total_freq;
run;
proc cancorr data=take all vprefix=u wprefix=v;
var buy_total_daydiff
buy_total_maxDay
buy_total_CT
buy_total_OZ
buy_total_LT; 
with buy_total_amount
buy_total_freq;
run;
